linters:
  enable:
    - unused
    - ineffassign
    - gofmt
    - goimports
    - govet
    - errcheck

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - unused

run:
  timeout: 5m
